name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: .deno
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.39.1'
      - run: deno task test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.39.1'
      - run: deno task lint